version: '3.9'
services:
  users-service:
    build:
      context: ./usersService
      args:
          PORT: 3000
    env_file: ./usersService/.env
    ports:
      - "3000:3000"
  books-service:
    build:
      context: ./booksService
      args:
          PORT: 3000
    env_file: ./booksService/.env
    ports:
      - "3001:3000"
  recommendations-service:
    build:
      context: ./recommendationsService
      args:
          PORT: 3000
    env_file: ./recommendationsService/.env
    ports:
      - "3002:3000"
