# Create stg-secret.yaml + prod-secret.yaml -> values as BASE64
apiVersion: v1
kind: Secret
metadata:
  name: books-service-secrets
  namespace: tf-tutorial
type: Opaque
data:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  POSTGRES_HOST:
  POSTGRES_PORT:
  POSTGRES_DB:
